import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { projectIdentity } from './project-identity.ts';
import { geminiWorkspaceTreeErrors, distributionTreeErrors, claudeDistributionTreeErrors, codexTreeErrors, INSTRUCTIONS_MARKER } from './tree-shape.ts';
import { walkFilesAbs } from './lib/fs.ts';

const root = path.resolve(import.meta.dirname, '..');
const srcDir = path.join(root, 'src');
const templatesDir = path.join(root, 'templates');

/** Gemini workspace compile output — separate from ephemeral handoff dirs under `.agents/`. */
export const AGENTS_BUILD_ROOT = path.join('.agents', 'build');
export const AGENTS_BUILD_AGENT_DIR = '.agents/build';
export const AGENTS_BUILD_VCODES = '.agents/build/rules/blackhole-vcodes.md';

/** Redistributable Antigravity plugin bundle — co-located plugin.json + skills/ + rules/, no agents/. */
export const DISTRIBUTION_ROOT = path.join('plugins', 'blackhole');
export const DISTRIBUTION_AGENT_DIR = 'plugins/blackhole';
export const DISTRIBUTION_VCODES = 'plugins/blackhole/rules/blackhole-vcodes.md';

/** Redistributable Claude Code marketplace bundle (ADR-009) — co-located
 * .claude-plugin/plugin.json + agents/ + skills/ + rules/ + templates/. Unlike the Gemini
 * distribution bundle above, this bundle SHIPS agents/: Claude marketplace plugins ship the 8
 * campaign agents, and AC4's no-agents rule is Gemini/Antigravity-schema-scoped only. Isolates
 * the intentionally-shipped plugin surface from maintainer-only repo-root `.claude/` content
 * (issue #262). */
export const CLAUDE_DISTRIBUTION_ROOT = path.join('plugins', 'blackhole-claude');
export const CLAUDE_DISTRIBUTION_AGENT_DIR = 'plugins/blackhole-claude';
export const CLAUDE_DISTRIBUTION_VCODES = 'plugins/blackhole-claude/rules/blackhole-vcodes.md';
const version = projectIdentity.version;

// ADR-007 T2 (R5′): tracked ⇒ built-by-default. Any build output already tracked by git is
// regenerated by plain `bun run build` — no opt-in flag required. `--gemini`/`--all`/`--no-codex`
// are retained as parsed-but-ignored deprecation aliases for one release (see step-0 audit
// below); an opt-in flag survives ONLY for a target that is genuinely untracked (ADR-007 Risk
// Assessment row 4) — that is the one legitimate residual use of these flags.
export const GEMINI_TARGET_DIRS = [AGENTS_BUILD_ROOT, '.gemini-plugin', DISTRIBUTION_ROOT];
export const CODEX_TARGET_DIRS = ['codex-agents', 'codex-skills', '.codex-plugin'];
export const DEPRECATED_BUILD_FLAGS = ['--gemini', '--all', '--no-codex'] as const;

/**
 * Step-0 tracking audit: does at least one of `paths` (relative to `rootDir`) contain a
 * git-tracked file? Used to decide whether a build target's opt-in flag can retire (tracked)
 * or must survive (genuinely untracked) — never collapsed onto a hardcoded assumption.
 */
export function isTargetTracked(rootDir: string, paths: string[]): boolean {
  for (const p of paths) {
    try {
      const out = execFileSync('git', ['ls-files', '--', p], { cwd: rootDir, encoding: 'utf-8' });
      if (out.trim().length > 0) return true;
    } catch {
      // git invocation failed (e.g. path outside a repo) — treat as untracked, not an error.
    }
  }
  return false;
}

const args = new Set(process.argv.slice(2));

export const cleanDir = (dirPath: string) => {
  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
  }
};

// Strip Cursor-only MDC frontmatter (--- globs: / alwaysApply: ---) for non-Cursor targets.
// The frontmatter block is kept as-is for Cursor; for Claude and skills.sh it is removed entirely
// since those platforms do not understand Cursor rule metadata.
const stripCursorFrontmatter = (content: string): string => {
  return content.replace(/^---\n(?:.*\n)*?---\n\n?/, '');
};

// Parse YAML frontmatter from markdown — body is everything after the first closing --- only.
export const parseMdFrontmatter = (content: string): { frontmatter: string; body: string } => {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { frontmatter: '', body: content };
  return { frontmatter: match[1], body: match[2] };
};

export const parseFrontmatterFields = (fmContent: string): Record<string, string> => {
  const fm: Record<string, string> = {};
  for (const line of fmContent.split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.substring(0, colonIdx).trim();
    const val = line.substring(colonIdx + 1).trim();
    if (key) fm[key] = val;
  }
  return fm;
};

export const parseDisallowedTools = (fm: Record<string, string>): string[] => {
  if (!fm.disallowedTools) return [];
  const m = fm.disallowedTools.match(/\[(.*)\]/);
  if (!m || !m[1].trim()) return [];
  return m[1].split(',').map((t) => t.trim()).filter(Boolean);
};

export const serializeCodexAgentYaml = (fm: Record<string, string>, bodyContent: string): string => {
  const tools = parseDisallowedTools(fm);
  let yaml = '';
  yaml += `name: ${fm.name || ''}\n`;
  yaml += `description: ${fm.description || ''}\n`;
  if (fm.model) yaml += `model: ${fm.model}\n`;
  yaml += `permissionMode: ${fm.permissionMode || ''}\n`;
  if (tools.length > 0) {
    yaml += `disallowedTools:\n`;
    for (const tool of tools) yaml += `  - ${tool}\n`;
  } else {
    yaml += `disallowedTools: []\n`;
  }
  const indentedBody = bodyContent
    .split('\n')
    .map((line) => (line ? `  ${line}` : ''))
    .join('\n');
  yaml += `${INSTRUCTIONS_MARKER}\n${indentedBody}\n`;
  return yaml;
};

export const buildCodexAgentYaml = (
  sourceContent: string,
  agentDir: string,
  rulesPath: string
): string => {
  const { frontmatter, body } = parseMdFrontmatter(sourceContent);
  const fm = parseFrontmatterFields(frontmatter);
  let bodyContent = applyPlatformConditionals(body, 'codex');
  bodyContent = compileContent(bodyContent, agentDir, rulesPath, 'codex');
  return serializeCodexAgentYaml(fm, bodyContent.trim());
};

// Enrich Cursor MDC frontmatter with glob patterns so the rule auto-applies on matching files.
const enrichVcodesMdcGlobs = (content: string): string => {
  return content.replace(
    'globs:\nalwaysApply: false',
    'globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.go", "**/*.py", "**/*.rs", "**/*.java", "**/*.c", "**/*.cpp", "**/*.cs"]\nalwaysApply: false'
  );
};

type Target = 'cursor' | 'claude' | 'skills' | 'gemini' | 'codex';

// Strip platform-conditional blocks: {{#cursor}}...{{/cursor}} etc.
// Keeps only the block matching the current compile target.
export const applyPlatformConditionals = (content: string, target: Target): string => {
  const active = target === 'skills' ? 'skills' : target;
  let res = content;
  for (const platform of ['cursor', 'claude', 'skills', 'gemini', 'codex'] as const) {
    if (platform !== active) {
      res = res.replace(new RegExp(`\\{\\{#${platform}\\}\\}[\\s\\S]*?\\{\\{/${platform}\\}\\}\\n?`, 'g'), '');
    }
  }
  res = res.replace(new RegExp(`\\{\\{#${active}\\}\\}`, 'g'), '');
  res = res.replace(new RegExp(`\\{\\{/${active}\\}\\}\\n?`, 'g'), '');
  return res;
};

export const compileContent = (content: string, agentDir: string, rulesPath: string, target: Target): string => {
  let res = content;
  if (target === 'codex') {
    res = res.replaceAll('{{AGENT_DIR}}/skills/blackhole/', 'codex-skills/blackhole/');
  }
  if (agentDir === '') {
    // skills.sh root layout: flat references/ at repo root
    res = res.replaceAll('{{AGENT_DIR}}/skills/blackhole/', '');
    res = res.replaceAll('{{AGENT_DIR}}', '');
  } else {
    res = res.replaceAll('{{AGENT_DIR}}', agentDir);
  }
  res = res.replaceAll('{{VCODES_PATH}}', rulesPath);
  if (target === 'skills' && agentDir !== '') {
    res = res.replaceAll('skills/blackhole/skills/blackhole/', 'skills/blackhole/');
  }
  return res;
};

// Footer-appended "generated, do not hand-edit" marker — never a header, since a header would
// break parseMdFrontmatter()'s requirement that frontmatter start at byte 0 of the file.
export const generatedMarkerLine = (relSrcPath: string, style: 'html' | 'yaml'): string => {
  const text = `GENERATED by scripts/build.ts from ${relSrcPath} — do not hand-edit`;
  return style === 'yaml' ? `# ${text}` : `<!-- ${text} -->`;
};

const processFile = (
  srcPath: string,
  destPath: string,
  agentDir: string,
  rulesPath: string,
  target: Target,
  isVcodesMdc = false,
  isAgent = false,
  isSkill = false
) => {
  const originalContent = fs.readFileSync(srcPath, 'utf-8');
  const relSrcPath = path.relative(root, srcPath).split(path.sep).join('/');

  const destDir = path.dirname(destPath);
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  // Codex agents: parse frontmatter from original source; compile body only
  if (isAgent && target === 'codex') {
    const yaml = buildCodexAgentYaml(originalContent, agentDir, rulesPath);
    const markedYaml = `${yaml}\n${generatedMarkerLine(relSrcPath, 'yaml')}\n`;
    fs.writeFileSync(destPath, markedYaml, 'utf-8');
    return;
  }

  let content = originalContent;

  if (target === 'cursor') {
    // Cursor: enrich vcodes .mdc with glob patterns
    if (isVcodesMdc) {
      content = enrichVcodesMdcGlobs(content);
    }
  } else if (isAgent && (target === 'claude' || target === 'gemini' || target === 'codex')) {
    // Claude/Gemini/Codex agents: preserve frontmatter (name, description, disallowedTools; model omitted by design)
    // — do not strip; Codex serializes frontmatter into YAML separately
  } else if (target === 'codex' && isSkill) {
    // Codex skill: preserve skill frontmatter (disable-model-invocation, name, description)
  } else {
    // Claude rules / skills.sh / Gemini rules: strip Cursor-only MDC frontmatter entirely
    content = stripCursorFrontmatter(content);
  }

  content = applyPlatformConditionals(content, target);
  const compiled = compileContent(content, agentDir, rulesPath, target);
  const separator = compiled.endsWith('\n') ? '' : '\n';
  const marked = `${compiled}${separator}${generatedMarkerLine(relSrcPath, 'html')}\n`;

  fs.writeFileSync(destPath, marked, 'utf-8');
};

// ADR-007 R6: recurses via the one shared tree-walker (scripts/lib/fs.ts) instead of a local
// readdirSync/stat recursion — after this migration, zero recursive directory walkers remain
// outside scripts/lib/fs.ts (V-INT-02).
const compileFolder = (srcSub: string, destParent: string, agentDir: string, rulesPath: string, target: Target, isAgent = false) => {
  const fullSrc = path.join(srcDir, srcSub);
  if (!fs.existsSync(fullSrc)) return;

  for (const srcPath of walkFilesAbs(fullSrc)) {
    const relFile = path.relative(fullSrc, srcPath);
    // Codex agents are output as .yaml instead of .md
    const destFile = (isAgent && target === 'codex' && relFile.endsWith('.md'))
      ? relFile.replace(/\.md$/, '.yaml')
      : relFile;
    const destPath = path.join(destParent, destFile);
    processFile(srcPath, destPath, agentDir, rulesPath, target, false, isAgent);
  }
};

// § facts — machine-checkable ground truth, declared exactly once (ADR-007 T3/R1′). verify.ts's
// facts-conformance check (V-GROUND-01) compares an independent filesystem/doc scan against
// these declarations — never restate any of these as an inline literal at a consumption site,
// and never collapse the scan and the declaration onto one derivation path (the critics'
// binding rejection of single-source generation, ADR-007 Rejected Alternatives).

export const RULES_LIST = ['blackhole-protocol.md', 'blackhole-state.md', 'blackhole-vcodes.md', 'doc-governance.md'];

/** The 8 agent files — bare names (no prefix) since the Blackhole rename (#64). */
export const AGENT_NAMES = ['coordinator', 'orchestrator', 'planner', 'implementer', 'reviewer', 'router', 'investigator', 'hunter'] as const;
export const AGENT_MD_FILES = new Set(AGENT_NAMES.map((n) => `${n}.md`));
export const AGENT_YAML_FILES = new Set(AGENT_NAMES.map((n) => `${n}.yaml`));

/** Exact phase strings used in `queue.json` `issues.*.phase` (V-PHASE-01). */
export const PHASE_NAMES = ['handle', 'plan', 'implement', 'review', 'done'] as const;

/** The 5 phase-playbook files under `src/references/` — note the terminal `done` phase loops
 *  back via `phase-loop.md`, it has no dedicated `phase-done.md` file (V-PHASE-01/V-GROUND-01). */
export const PHASE_PLAYBOOK_FILES = ['phase-handle.md', 'phase-plan.md', 'phase-implement.md', 'phase-review.md', 'phase-loop.md'];

/** References every phase playbook assumes exist under `src/references/` (V-GROUND-01). */
export const REQUIRED_REFERENCES = ['review-core.md', 'worker-schemas.md', 'checkpoint-protocol.md'];

/** Row count of `src/references/blackhole-vcodes.md`'s `| V-...` table (V-GROUND-01). */
export const VCODE_TABLE_ROW_COUNT = 51;

/**
 * Total check count across every `scripts/checks/*.check.ts` domain file (ADR-007 T5/R2′:
 * `verify.ts` is a thin runner that glob-discovers these files — there is no central registry).
 * Bump this alongside any change to a domain file's `runChecks()` array — either adding a new
 * `scripts/checks/{domain}.check.ts` file (new domain, its own `runChecks()` contributing its
 * count), or adding/removing an individual check inside an existing domain's `runChecks()`
 * array. `verify.ts` warns (does not fail) on a mismatch, so this is the sole place the
 * expectation is declared — never restate it as a literal at any consumption site.
 */
export const EXPECTED_CHECK_COUNT = 30;

export const buildGeminiPluginManifest = (pkgVersion: string) => ({
  $schema: 'https://antigravity.google/schemas/v1/plugin.json',
  name: projectIdentity.name,
  description: projectIdentity.description,
  version: pkgVersion,
  author: { name: 'blackhole contributors' },
  license: 'Apache-2.0',
  keywords: [projectIdentity.name, 'gemini', ...projectIdentity.keywordsBase],
});

export const buildCodexPluginManifest = (pkgVersion: string) => ({
  name: projectIdentity.name,
  version: pkgVersion,
  description: projectIdentity.description,
  author: {
    name: 'Corentin Lumineau',
    email: 'corentin@lumineau.dev',
    url: 'https://github.com/CorentinLumineau',
  },
  homepage: projectIdentity.homepage,
  repository: projectIdentity.repository,
  license: 'Apache-2.0',
  keywords: [projectIdentity.name, 'codex', ...projectIdentity.keywordsBase],
  skills: './codex-skills/',
  interface: {
    displayName: 'Blackhole',
    shortDescription: 'Auto-solve your entire GitHub backlog',
    longDescription: 'Five-phase lifecycle: Handle → Plan → Implement → Review → Loop.',
    developerName: 'Corentin Lumineau',
    category: 'Developer Tools',
    capabilities: ['Write', 'Interactive'],
    websiteURL: projectIdentity.repository,
    defaultPrompt: [
      'Run the backlog campaign until empty for this repo.',
      'Show backlog status: open issues, in-flight, and queue.',
      'Implement issue #N using the campaign pipeline.',
    ],
    brandColor: '#3B82F6',
  },
});

export const buildCodexMarketplace = () => ({
  name: `${projectIdentity.name}-codex`,
  interface: { displayName: 'Blackhole - Codex' },
  plugins: [
    {
      name: projectIdentity.name,
      source: {
        source: 'git',
        url: projectIdentity.repository,
      },
      policy: {
        installation: 'AVAILABLE',
        authentication: 'ON_INSTALL',
      },
      category: 'Developer Tools',
    },
  ],
});

export const buildClaudePluginManifest = (pkgVersion: string) => ({
  name: projectIdentity.name,
  description: projectIdentity.description,
  version: pkgVersion,
  author: { name: 'blackhole contributors' },
  license: 'Apache-2.0',
  keywords: [projectIdentity.name, 'claude-code', ...projectIdentity.keywordsBase],
});

/** `source` points at the isolated Claude marketplace bundle (ADR-009, issue #262) rather than
 * the repo root — Claude Code resolves a relative `"./..."` source against the marketplace root
 * (the dir containing `.claude-plugin/`), so this keeps maintainer-only repo-root `.claude/`
 * content out of every consumer's install surface. */
export const buildClaudeMarketplace = (pluginMeta: ReturnType<typeof buildClaudePluginManifest>) => ({
  name: `${projectIdentity.name}-marketplace`,
  description: 'Blackhole Marketplace',
  owner: { name: 'CorentinLumineau' },
  plugins: [{ ...pluginMeta, source: `./${CLAUDE_DISTRIBUTION_ROOT.split(path.sep).join('/')}` }],
});

/** Copies templates/companion-files/ (repo root, not src/) into destRoot's own
 * templates/companion-files/ subtree. Isolated distribution bundles need their own copy since
 * they don't ship at the repo root: the Gemini/Antigravity bundle (plugins/blackhole/) and, since
 * ADR-009 (issue #262), the Claude Code marketplace bundle (plugins/blackhole-claude/) — both
 * call this via compileGeminiTree. Cursor and Codex still install via full-repo-source/committed
 * mechanisms and already have templates/ at its natural repo-relative path with zero
 * build-pipeline change. */
export const copyTemplatesDir = (destRoot: string) => {
  const src = path.join(templatesDir, 'companion-files');
  if (!fs.existsSync(src)) return;
  const dest = path.join(destRoot, 'templates', 'companion-files');
  fs.cpSync(src, dest, { recursive: true });
};

/**
 * Compiles a full plugin tree — agents? + rules + SKILL.md + references + templates — for a
 * given platform `target` (default 'gemini', preserving every existing call site's behavior
 * unchanged). Reused as-is for the Claude Code marketplace distribution bundle (ADR-009, issue
 * #262) via `target: 'claude'`, since `applyPlatformConditionals` resolves `{{#claude}}`/
 * `{{#gemini}}` blocks differently per target — passing the wrong `target` for a destination
 * would silently compile the wrong platform's conditional content into it. Parameterizing the
 * existing walker (rather than hand-rolling a second one) keeps V-INT-02: the recursion itself
 * still runs through `walkFilesAbs` (scripts/lib/fs.ts) via `compileFolder`.
 */
export const compileGeminiTree = (
  destRoot: string,
  agentDir: string,
  rulesPath: string,
  options: { includeAgents?: boolean; target?: Target } = {}
) => {
  const target = options.target ?? 'gemini';
  if (options.includeAgents !== false) {
    compileFolder('agents', path.join(destRoot, 'agents'), agentDir, rulesPath, target, true);
  }
  for (const rule of RULES_LIST) {
    processFile(
      path.join(srcDir, 'references', rule),
      path.join(destRoot, 'rules', rule),
      agentDir,
      rulesPath,
      target
    );
  }
  processFile(
    path.join(srcDir, 'SKILL.md'),
    path.join(destRoot, 'skills', 'blackhole', 'SKILL.md'),
    agentDir,
    rulesPath,
    target
  );
  compileFolder(
    'references',
    path.join(destRoot, 'skills', 'blackhole', 'references'),
    agentDir,
    rulesPath,
    target
  );
  copyTemplatesDir(destRoot);
};

export const writeGeminiManifest = (destPath: string, manifest: Record<string, unknown>) => {
  const destDir = path.dirname(destPath);
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }
  fs.writeFileSync(destPath, JSON.stringify(manifest, null, 2), 'utf-8');
};

export const compileCodexTree = (rootDir: string, agentDir: string, rulesPath: string) => {
  compileFolder('agents', path.join(rootDir, 'codex-agents'), agentDir, rulesPath, 'codex', true);
  processFile(
    path.join(srcDir, 'SKILL.md'),
    path.join(rootDir, 'codex-skills', 'blackhole', 'SKILL.md'),
    agentDir,
    rulesPath,
    'codex',
    false,
    false,
    true
  );
  compileFolder(
    'references',
    path.join(rootDir, 'codex-skills', 'blackhole', 'references'),
    agentDir,
    rulesPath,
    'codex'
  );
};

// 1. Resolve deprecated-flag warnings and decide which opt-in targets build this run.
const determineBuildTargets = (): { buildGemini: boolean; buildCodex: boolean } => {
  for (const flag of DEPRECATED_BUILD_FLAGS) {
    if (args.has(flag)) {
      console.error(
        `[build] ${flag} is deprecated and now a no-op — every git-tracked build target is ` +
          'regenerated by default (ADR-007 T2). Scheduled for removal next release.'
      );
    }
  }

  const geminiTracked = isTargetTracked(root, GEMINI_TARGET_DIRS);
  const codexTracked = isTargetTracked(root, CODEX_TARGET_DIRS);
  if (!geminiTracked) {
    console.error(
      '[build] gemini build targets are not tracked in git yet — pass --gemini or --all to opt in for this run.'
    );
  }
  if (!codexTracked) {
    console.error(
      '[build] codex build targets are not tracked in git yet — omit --no-codex (or pass --all) to opt in for this run.'
    );
  }

  // Tracked ⇒ built by default (ADR-007 T2/R5′). The opt-in flags only still matter for a
  // genuinely untracked target — once tracked, the flags below are inert no-ops (deprecation
  // notice printed above).
  const buildGemini = geminiTracked || args.has('--gemini') || args.has('--all');
  const buildCodex = codexTracked || !args.has('--no-codex');
  return { buildGemini, buildCodex };
};

const cleanBuildDirectories = (buildGemini: boolean, buildCodex: boolean) => {
  console.log('Cleaning existing build directories...');
  cleanDir(path.join(root, 'rules'));
  cleanDir(path.join(root, 'agents'));
  cleanDir(path.join(root, 'skills'));
  cleanDir(path.join(root, 'references'));
  cleanDir(path.join(root, '.cursor'));
  // Only clean the subdirs build.ts actually writes — `.claude/` also holds
  // maintainer state (initiatives/, progress.md) that must survive a rebuild.
  // `.claude/skills` is narrowed to the `blackhole/` subdir specifically (issue #267): build only
  // ever writes `.claude/skills/blackhole/`, so wiping the whole `skills/` dir deleted sibling
  // maintainer-only skills (e.g. `create-release/`) that live alongside it. `.claude/agents` and
  // `.claude/rules` still wipe wholesale — narrow them the same way only if maintainer agents/rules
  // are ever added (YAGNI; not done now, since build writes the entirety of both dirs today).
  cleanDir(path.join(root, '.claude', 'agents'));
  cleanDir(path.join(root, '.claude', 'rules'));
  cleanDir(path.join(root, '.claude', 'skills', 'blackhole'));
  cleanDir(path.join(root, '.claude-plugin'));
  // Claude marketplace distribution bundle (ADR-009) — unconditional like the rest of Target C
  // above, not gated behind the Gemini/Codex tracked-target opt-in flags: it is the redistributable
  // form of the always-built repo-root .claude/ Target C, not an optional bonus target.
  cleanDir(path.join(root, CLAUDE_DISTRIBUTION_ROOT));
  if (buildGemini) {
    cleanDir(path.join(root, AGENTS_BUILD_ROOT));
    cleanDir(path.join(root, '.gemini-plugin'));
    cleanDir(path.join(root, DISTRIBUTION_ROOT));
  }
  if (buildCodex) {
    cleanDir(path.join(root, 'codex-agents'));
    cleanDir(path.join(root, 'codex-skills'));
    cleanDir(path.join(root, '.codex-plugin'));
  }
  if (fs.existsSync(path.join(root, 'SKILL.md'))) {
    fs.unlinkSync(path.join(root, 'SKILL.md'));
  }
  if (buildCodex && fs.existsSync(path.join(root, 'codex-marketplace.json'))) {
    fs.unlinkSync(path.join(root, 'codex-marketplace.json'));
  }
};

// 2. Compile Target A: Agent-Agnostic / skills.sh (Root level flat layout)
const compileSkillsTarget = () => {
  console.log('Compiling Target A (skills.sh root-level)...');
  processFile(
    path.join(srcDir, 'SKILL.md'),
    path.join(root, 'SKILL.md'),
    '',
    'references/blackhole-vcodes.md',
    'skills'
  );
  compileFolder(
    'references',
    path.join(root, 'references'),
    '',
    'references/blackhole-vcodes.md',
    'skills'
  );
};

// 3. Compile Target B: Cursor (submodule root layout + .cursor/ mirror)
const compileCursorTarget = () => {
  console.log('Compiling Target B (Cursor)...');
  const cursorAgentDir = '.cursor';
  const cursorVcodesPath = '.cursor/rules/blackhole-vcodes.mdc';

  const writeCursorRules = (destDir: string) => {
    for (const rule of RULES_LIST) {
      const isVcodesMdc = rule === 'blackhole-vcodes.md';
      const destName = rule.substring(0, rule.length - 3) + '.mdc';
      processFile(
        path.join(srcDir, 'references', rule),
        path.join(destDir, destName),
        cursorAgentDir,
        cursorVcodesPath,
        'cursor',
        isVcodesMdc
      );
    }
  };

  writeCursorRules(path.join(root, 'rules'));
  writeCursorRules(path.join(root, '.cursor', 'rules'));

  /** Project maintainer rules (not plugin SSOT) — survive cleanDir; copied into Cursor rules dir. */
  const copyMaintainerCursorRules = (destDir: string) => {
    const maintainerRulesDir = path.join(root, '.github', 'rules');
    if (!fs.existsSync(maintainerRulesDir)) return;
    for (const file of fs.readdirSync(maintainerRulesDir)) {
      if (!file.endsWith('.mdc')) continue;
      fs.copyFileSync(path.join(maintainerRulesDir, file), path.join(destDir, file));
    }
  };
  copyMaintainerCursorRules(path.join(root, '.cursor', 'rules'));
  compileFolder('agents', path.join(root, 'agents'), cursorAgentDir, cursorVcodesPath, 'cursor', true);
  compileFolder('agents', path.join(root, '.cursor', 'agents'), cursorAgentDir, cursorVcodesPath, 'cursor', true);
  processFile(path.join(srcDir, 'SKILL.md'), path.join(root, 'skills', 'blackhole', 'SKILL.md'), cursorAgentDir, cursorVcodesPath, 'cursor');
  processFile(path.join(srcDir, 'SKILL.md'), path.join(root, '.cursor', 'skills', 'blackhole', 'SKILL.md'), cursorAgentDir, cursorVcodesPath, 'cursor');
  compileFolder('references', path.join(root, 'skills', 'blackhole', 'references'), cursorAgentDir, cursorVcodesPath, 'cursor');
  compileFolder('references', path.join(root, '.cursor', 'skills', 'blackhole', 'references'), cursorAgentDir, cursorVcodesPath, 'cursor');
};

// 4. Compile Target C: Claude Project-Level Native (.claude/)
const compileClaudeNativeTarget = () => {
  console.log('Compiling Target C (Claude Project Native)...');
  compileFolder(
    'agents',
    path.join(root, '.claude', 'agents'),
    '.claude',
    '.claude/rules/blackhole-vcodes.md',
    'claude',
    true
  );
  for (const rule of RULES_LIST) {
    processFile(
      path.join(srcDir, 'references', rule),
      path.join(root, '.claude', 'rules', rule),
      '.claude',
      '.claude/rules/blackhole-vcodes.md',
      'claude'
    );
  }
  processFile(
    path.join(srcDir, 'SKILL.md'),
    path.join(root, '.claude', 'skills', 'blackhole', 'SKILL.md'),
    '.claude',
    '.claude/rules/blackhole-vcodes.md',
    'claude'
  );
  compileFolder(
    'references',
    path.join(root, '.claude', 'skills', 'blackhole', 'references'),
    '.claude',
    '.claude/rules/blackhole-vcodes.md',
    'claude'
  );
};

// 4b. Compile Target C2: Claude Code marketplace distribution bundle (plugins/blackhole-claude/)
// — ADR-009, issue #262. Isolates the intentionally-shipped plugin surface (skill + 8 campaign
// agents + rules + templates) from maintainer-only repo-root .claude/ content. Unlike the Gemini
// distribution bundle (Target D2 below), this bundle SHIPS agents/ — Claude marketplace plugins
// ship agents; AC4's no-agents rule is Gemini/Antigravity-schema-scoped only.
// Returns claudeDistRoot so downstream steps (Target D2's manifest bundling and Codex's later
// steps do not need it, but generateClaudePluginManifests does) can reuse it without recomputing.
const compileClaudeMarketplaceTarget = (): string => {
  console.log('Compiling Claude Code marketplace bundle (plugins/blackhole-claude/)...');
  const claudeDistRoot = path.join(root, CLAUDE_DISTRIBUTION_ROOT);
  compileGeminiTree(claudeDistRoot, CLAUDE_DISTRIBUTION_AGENT_DIR, CLAUDE_DISTRIBUTION_VCODES, {
    includeAgents: true,
    target: 'claude',
  });
  return claudeDistRoot;
};

// 5. Compile Target D: Gemini/Antigravity — workspace (.agents/build/) — opt-in (#13)
const compileGeminiTargets = (buildGemini: boolean) => {
  if (!buildGemini) return;
  console.log('Compiling Target D (Gemini/Antigravity workspace — .agents/build/)...');
  const agentsBuildRoot = path.join(root, AGENTS_BUILD_ROOT);
  compileGeminiTree(agentsBuildRoot, AGENTS_BUILD_AGENT_DIR, AGENTS_BUILD_VCODES);
  const workspaceAgentsDir = path.join(agentsBuildRoot, 'agents');
  const workspaceAgentFiles = fs.existsSync(workspaceAgentsDir)
    ? fs.readdirSync(workspaceAgentsDir).filter((f) => AGENT_MD_FILES.has(f))
    : [];
  const workspaceErrors = geminiWorkspaceTreeErrors(agentsBuildRoot, 'workspace', RULES_LIST, workspaceAgentFiles, AGENT_NAMES.length);
  if (workspaceErrors.length) throw new Error(workspaceErrors.join('; '));

  console.log('Generating Gemini Plugin manifest...');
  const geminiPluginMeta = buildGeminiPluginManifest(version);

  // Detached manifest for marketplace metadata (same payload as co-located plugin.json).
  writeGeminiManifest(path.join(root, '.gemini-plugin', 'plugin.json'), geminiPluginMeta);

  // Distribution bundle: redistributable plugin co-located with skills/ and rules/, no agents/
  // (AC4). Independent write site from the detached manifest above — each block is deletable
  // without breaking the other (see Grounding in .blackhole/plans/issue-27.md).
  console.log('Compiling Target D2 (Gemini/Antigravity distribution bundle — plugins/blackhole/)...');
  const distributionRoot = path.join(root, DISTRIBUTION_ROOT);
  compileGeminiTree(distributionRoot, DISTRIBUTION_AGENT_DIR, DISTRIBUTION_VCODES, { includeAgents: false });
  writeGeminiManifest(path.join(distributionRoot, 'plugin.json'), geminiPluginMeta);
  const distributionErrors = distributionTreeErrors(
    distributionRoot,
    path.join(distributionRoot, 'plugin.json'),
    RULES_LIST
  );
  if (distributionErrors.length) throw new Error(distributionErrors.join('; '));
};

// 6. Generate Claude Code Plugin Manifest (.claude-plugin/plugin.json)
// 6b. Bundle manifest: same payload as the repo-root manifest above, written to its own
// .claude-plugin/plugin.json *inside* the isolated distribution bundle (ADR-009) — the Claude
// plugin schema requires the manifest co-located with the plugin, unlike Gemini's flat
// plugin.json at bundle root (buildGeminiPluginManifest / writeGeminiManifest above).
// 8. Generate Claude Code Marketplace Catalog (.claude-plugin/marketplace.json)
const generateClaudePluginManifests = (claudeDistRoot: string) => {
  console.log('Generating Claude Code Plugin manifests...');
  const pluginMeta = buildClaudePluginManifest(version);
  const pluginDir = path.join(root, '.claude-plugin');
  if (!fs.existsSync(pluginDir)) fs.mkdirSync(pluginDir, { recursive: true });
  fs.writeFileSync(path.join(pluginDir, 'plugin.json'), JSON.stringify(pluginMeta, null, 2), 'utf-8');

  const claudeBundlePluginDir = path.join(claudeDistRoot, '.claude-plugin');
  if (!fs.existsSync(claudeBundlePluginDir)) fs.mkdirSync(claudeBundlePluginDir, { recursive: true });
  fs.writeFileSync(path.join(claudeBundlePluginDir, 'plugin.json'), JSON.stringify(pluginMeta, null, 2), 'utf-8');

  const claudeBundleAgentsDir = path.join(claudeDistRoot, 'agents');
  const claudeBundleAgentFiles = fs.existsSync(claudeBundleAgentsDir)
    ? fs.readdirSync(claudeBundleAgentsDir).filter((f) => AGENT_MD_FILES.has(f))
    : [];
  const claudeDistErrors = claudeDistributionTreeErrors(claudeDistRoot, claudeBundleAgentFiles, AGENT_NAMES.length, RULES_LIST);
  if (claudeDistErrors.length) throw new Error(claudeDistErrors.join('; '));

  const marketplaceJson = buildClaudeMarketplace(pluginMeta);
  fs.writeFileSync(path.join(pluginDir, 'marketplace.json'), JSON.stringify(marketplaceJson, null, 2), 'utf-8');
};

// 9. Compile Target E: Codex CLI Native Support (default build — #31)
const compileCodexTarget = (buildCodex: boolean) => {
  if (!buildCodex) return;
  console.log('Compiling Target E (Codex CLI Support)...');
  const codexAgentDir = 'codex-skills';
  const codexVcodesPath = 'codex-skills/blackhole/references/blackhole-vcodes.md';
  compileCodexTree(root, codexAgentDir, codexVcodesPath);
  const codexAgentsDir = path.join(root, 'codex-agents');
  const codexAgentFiles = fs.existsSync(codexAgentsDir)
    ? fs.readdirSync(codexAgentsDir).filter((f) => AGENT_YAML_FILES.has(f))
    : [];
  const codexErrors = codexTreeErrors(root, codexAgentFiles, AGENT_NAMES.length);
  if (codexErrors.length) throw new Error(codexErrors.join('; '));

  console.log('Generating Codex Plugin manifest...');
  const codexPluginMeta = buildCodexPluginManifest(version);
  const codexPluginDir = path.join(root, '.codex-plugin');
  if (!fs.existsSync(codexPluginDir)) fs.mkdirSync(codexPluginDir, { recursive: true });
  fs.writeFileSync(path.join(codexPluginDir, 'plugin.json'), JSON.stringify(codexPluginMeta, null, 2), 'utf-8');

  const codexMarketplaceJson = buildCodexMarketplace();
  fs.writeFileSync(path.join(root, 'codex-marketplace.json'), JSON.stringify(codexMarketplaceJson, null, 2), 'utf-8');
};

const main = () => {
  const { buildGemini, buildCodex } = determineBuildTargets();
  cleanBuildDirectories(buildGemini, buildCodex);
  compileSkillsTarget();
  compileCursorTarget();
  compileClaudeNativeTarget();
  const claudeDistRoot = compileClaudeMarketplaceTarget();
  compileGeminiTargets(buildGemini);
  generateClaudePluginManifests(claudeDistRoot);
  compileCodexTarget(buildCodex);

  console.log('Build compilation completed successfully!');
};

if (import.meta.main) {
  main();
}
