import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { readJsonFile } from './lib/fs.ts';

const root = path.resolve(import.meta.dirname, '..');

export type ReleaseDeps = {
  build?: () => void;
  execGit?: (cmd: string) => string;
};

function repoPaths(repoRoot: string) {
  const releasesDir = path.join(repoRoot, '.github', 'releases');
  return {
    releasesDir,
    templatePath: path.join(releasesDir, 'TEMPLATE.md'),
    pkgPath: path.join(repoRoot, 'package.json'),
  };
}

function usage(): never {
  console.log(`Usage:
  bun run release prepare <vX.Y.Z>   Copy TEMPLATE → notes file, bump package.json
  bun run release validate <vX.Y.Z>  Verify notes file, version sync, clean tree
  bun run release tag <vX.Y.Z>       Validate + create annotated git tag on HEAD
  bun run release push <vX.Y.Z>      Push main + tag to origin (triggers CI release)`);
  process.exit(1);
}

export function normalizeTag(tag: string): string {
  const t = tag.trim();
  if (!/^v\d+\.\d+\.\d+$/.test(t)) {
    console.error(`Invalid tag "${tag}". Expected format: vX.Y.Z`);
    process.exit(1);
  }
  return t;
}

function versionFromTag(tag: string): string {
  return tag.startsWith('v') ? tag.slice(1) : tag;
}

function notesPath(releasesDir: string, tag: string): string {
  return path.join(releasesDir, `${tag}.md`);
}

function readPkg(pkgPath: string): { version: string; [k: string]: unknown } {
  return readJsonFile(pkgPath, pkgPath) as { version: string; [k: string]: unknown };
}

function writePkg(pkgPath: string, pkg: { version: string; [k: string]: unknown }): void {
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
}

function createGit(repoRoot: string, deps?: ReleaseDeps) {
  return (cmd: string): string => {
    if (deps?.execGit) {
      return deps.execGit(cmd).trim();
    }
    return execSync(cmd, { cwd: repoRoot, encoding: 'utf-8' }).trim();
  };
}

function build(): void {
  // ADR-007 T2 (R5′): every git-tracked build target is regenerated by plain `bun run build` —
  // `--all` is now a deprecation no-op alias, not a required flag.
  execSync('bun run build', { cwd: root, stdio: 'inherit' });
}

export const MANIFEST_PATHS: Array<{ path: string; versionOf: (json: unknown) => string | undefined }> = [
  { path: '.claude-plugin/plugin.json', versionOf: (json) => (json as { version?: string }).version },
  {
    path: '.claude-plugin/marketplace.json',
    versionOf: (json) => (json as { plugins?: Array<{ version?: string }> }).plugins?.[0]?.version,
  },
  { path: '.codex-plugin/plugin.json', versionOf: (json) => (json as { version?: string }).version },
  { path: '.gemini-plugin/plugin.json', versionOf: (json) => (json as { version?: string }).version },
  { path: 'plugins/blackhole/plugin.json', versionOf: (json) => (json as { version?: string }).version },
];

export function findManifestVersionMismatches(
  pkgVersion: string,
  manifests: Record<string, unknown>
): string[] {
  const mismatches: string[] = [];
  for (const { path: manifestPath, versionOf } of MANIFEST_PATHS) {
    if (versionOf(manifests[manifestPath]) !== pkgVersion) {
      mismatches.push(manifestPath);
    }
  }
  return mismatches;
}

function tagExists(git: (cmd: string) => string, tag: string): boolean {
  try {
    git(`git rev-parse refs/tags/${tag}`);
    return true;
  } catch {
    return false;
  }
}

function remoteTagExists(git: (cmd: string) => string, tag: string): boolean {
  try {
    const out = git(`git ls-remote --tags origin refs/tags/${tag}`);
    return out.length > 0;
  } catch {
    return false;
  }
}

export function validateRelease(
  repoRoot: string,
  tag: string,
  opts: { allowDirty?: boolean; deps?: ReleaseDeps } = {}
): void {
  const { releasesDir, pkgPath } = repoPaths(repoRoot);
  const git = createGit(repoRoot, opts.deps);
  const version = versionFromTag(tag);
  const notes = notesPath(releasesDir, tag);

  if (!fs.existsSync(notes)) {
    console.error(`Missing release notes: ${path.relative(repoRoot, notes)}`);
    console.error(`Run: bun run release prepare ${tag}`);
    process.exit(1);
  }

  const content = fs.readFileSync(notes, 'utf-8').trim();
  if (content.length < 100) {
    console.error(`Release notes too short (${content.length} chars): ${path.relative(repoRoot, notes)}`);
    process.exit(1);
  }

  const pkg = readPkg(pkgPath);
  if (pkg.version !== version) {
    console.error(`package.json version "${pkg.version}" does not match tag "${tag}" (expected ${version})`);
    process.exit(1);
  }

  if (tagExists(git, tag)) {
    console.error(`Tag ${tag} already exists locally. Delete it first if you intend to recreate.`);
    process.exit(1);
  }

  if (remoteTagExists(git, tag)) {
    console.error(`Tag ${tag} already exists on origin.`);
    process.exit(1);
  }

  if (!opts.allowDirty) {
    const status = git('git status --porcelain');
    if (status) {
      console.warn('Warning: working tree is not clean:');
      console.warn(status);
    }
  }

  console.log(`✓ ${tag} validated — notes file OK, package.json ${version}`);
}

export function prepareRelease(repoRoot: string, tag: string, deps?: ReleaseDeps): void {
  const { releasesDir, templatePath, pkgPath } = repoPaths(repoRoot);
  const version = versionFromTag(tag);
  const dest = notesPath(releasesDir, tag);

  if (!fs.existsSync(templatePath)) {
    console.error(`Missing template: ${path.relative(repoRoot, templatePath)}`);
    process.exit(1);
  }

  if (fs.existsSync(dest)) {
    console.error(`Release notes already exist: ${path.relative(repoRoot, dest)}`);
    process.exit(1);
  }

  let template = fs.readFileSync(templatePath, 'utf-8');
  template = template.replaceAll('vX.Y.Z', tag).replaceAll('X.Y.Z', version);
  fs.writeFileSync(dest, template, 'utf-8');

  const pkg = readPkg(pkgPath);
  pkg.version = version;
  writePkg(pkgPath, pkg);

  (deps?.build ?? build)();

  console.log(`Created ${path.relative(repoRoot, dest)}`);
  console.log(`Bumped package.json → ${version}`);
  console.log(`Ran bun run build — regenerated the 5 version-carrying manifests`);
  console.log('');
  console.log('Next steps:');
  console.log(`  1. Edit ${path.relative(repoRoot, dest)} with product-focused release notes`);
  console.log(`  2. bun run release validate ${tag}`);
  console.log(`  3. Commit notes + package.json + the 5 regenerated manifests, then push`);
  console.log(`  4. bun run release tag ${tag}`);
  console.log(`  5. bun run release push ${tag}`);
}

export function tagRelease(repoRoot: string, tag: string, deps?: ReleaseDeps): void {
  validateRelease(repoRoot, tag, { deps });
  const git = createGit(repoRoot, deps);
  const message = `Release ${tag}`;
  git(`git tag -a ${tag} -m "${message}"`);
  console.log(`✓ Created annotated tag ${tag} on ${git('git rev-parse --short HEAD')}`);
}

export function pushRelease(repoRoot: string, tag: string, deps?: ReleaseDeps): void {
  const git = createGit(repoRoot, deps);
  if (!tagExists(git, tag)) {
    console.error(`Tag ${tag} does not exist locally. Run: bun run release tag ${tag}`);
    process.exit(1);
  }
  git('git push origin main');
  git(`git push origin ${tag}`);
  console.log(`✓ Pushed main and ${tag} — CI will publish the GitHub release`);
}

function main(): void {
  const [, , command, rawTag] = process.argv;
  if (!command || !rawTag) usage();

  const tagArg = normalizeTag(rawTag);

  switch (command) {
    case 'prepare':
      prepareRelease(root, tagArg);
      break;
    case 'validate':
      validateRelease(root, tagArg);
      break;
    case 'tag':
      tagRelease(root, tagArg);
      break;
    case 'push':
      pushRelease(root, tagArg);
      break;
    default:
      usage();
  }
}

if (import.meta.main) {
  main();
}
